[tools]
tuist = "latest"

[env]
SENTRY_DISABLED = "true"

[tasks.archive]
run = "tuist xcodebuild build -project Walletify.xcodeproj -scheme 'Walletify Release' -configuration Release -destination 'generic/platform=iOS' -archivePath .archives/Walletify clean archive"
description = "Creates an archive of the app for distribution"

[tasks.create-ipa]
run = """xcodebuild \
  -exportArchive \
  -archivePath .archives/Walletify.xcarchive \
  -exportOptionsPlist ./ExportOptions.plist \
  -exportPath .archives/export
"""
description = "Creates an IPA file from the archive for distribution"
depends = ["archive"]

[tasks.release]
run = "tuist share .archives/export/Walletify.ipa"
description = "Creates a Tuist preview for the latest release build"
depends = ["create_ipa"]

[tasks."tuist:web"]
run = "tuist project show --web"
description = "Opens the Tuist web page for the project"
