schemaVersion: 1
enabledWorkflows:
  - debugging
  - logging
  - project-discovery
  - simulator
  - utilities
  - xcode-ide
  - doctor
debug: true
sentryDisabled: true
sessionDefaults:
  projectPath: Walletify.xcodeproj
  scheme: Walletify
  configuration: Debug
  simulatorName: iPhone 17 Pro
  simulatorId: BA8B48F5-4386-47F0-AC83-5B3192E3FC58
  deviceId: F3968B01-8621-597C-93A6-4A4514802442
  platform: iOS
