[tools]
cloudflared = "latest"

[tasks.tunnel]
run = "dotenvx run -f .env.cloudflare -- sh -c 'cloudflared tunnel run --token \"$CLOUDFLARED_TOKEN\"'"

[tasks.dev]
run = "dotenvx run -f .env -f .env.secrets -- bun run dev"

[tasks.debug]
run = "dotenvx run -f .env -f .env.secrets -- bun run debug"
