[tools]
cloudflared = "latest"

[tasks.tunnel]
run = "dotenvx run -f .env.cloudflare -- sh -c 'cloudflared tunnel run --token \"$CLOUDFLARED_TOKEN\"'"

[tasks.dev]
run = "dotenvx run -f .env -f .env.secrets -- bun run --watch src/main.ts"

[tasks.start]
run = "bun run build && dotenvx run -f .env -f .env.secrets -- ./server"

[tasks.debug]
run = "dotenvx run -f .env -f .env.secrets -- bun run --inspect-brk src/main.ts"
